### ISSUE TITLE
Unicorn Recorder does not show up after Update

### ISSUE THREAD

**Issue by flattinger** [unicorn-bi/Unicorn-Recorder-Hybrid-Black#1]
Unicorn Recorder is not showing in the "App" tab after installing the Update.

**Comment by unicorn-bi** [comment]
Fixed in 'Unicorn Suite Hybrid Black 1.24.00 BETA 2609'. Network connection timed out.

**Comment by unicorn-bi** [comment]
Fixed in 'Unicorn Suite Hybrid Black 1.24.00 BETA 2609'. Network connection timed out.
