### ISSUE TITLE
Batter level status not correct

### ISSUE THREAD

**Issue by flattinger** [unicorn-bi/Unicorn-Recorder-Hybrid-Black#10]
Unicorn Suite BETA 2621, Recorder BETA 2652, Platformer + Puzzle Game BETA 2628

In the Unicorn Recorder the battery status is displayed as full and the Unicorn also blinks cyan which indicates a good battery status. When we want to start the Platformer or Puzzle Game the battery level status is displayed as empty and after calibration the software says to "Charge" the battery. We are stuck in the calibration stage

**Comment by unicorn-bi** [comment]
moved to games repo
