### ISSUE TITLE
License Activation Issue

### ISSUE THREAD

**Issue by flattinger** [unicorn-bi/Unicorn-Recorder-Hybrid-Black#2]
When we tried to activate the Unicorn Recorder Hybrid License and we got the attached error
![activation_issue](https://github.com/unicorn-bi/Unicorn-Recorder-Hybrid-Black/assets/170942683/c5a454eb-ada2-46d8-8798-d0127501c026)

Unicorn Version 1.24.00 BETA 2609

**Comment by unicorn-bi** [comment]
fixed in beta 2621

**Comment by unicorn-bi** [comment]
fixed in beta 2621
