### ISSUE TITLE
Drop Down Menu Unicorn Recorder

### ISSUE THREAD

**Issue by gteclechner** [unicorn-bi/Unicorn-Recorder-Hybrid-Black#3]
![image_2024_07_09T07_57_30_678Z](https://github.com/unicorn-bi/Unicorn-Recorder-Hybrid-Black/assets/134391441/a633704c-24dd-4047-b881-af66c9a83ddf)

The drop-down menus for scaling, filtering, and notching are too long. The usual entries are several times there

**Comment by unicorn-bi** [comment]
should be fixed. bugfix will be deployed with next Unicorn Recorder release
