### ISSUE TITLE
Bluetooth Connection 

### ISSUE THREAD

**Issue by gteclechner** [unicorn-bi/Unicorn-Recorder-Hybrid-Black#4]
The distribution partner Kelvin Wong from UTE, Malaysia, reported that the Unicorn is not connecting regularly. After several tries, it is finally connecting. A log file has been requested but has not been sent yet.

**Comment by flattinger** [comment]
scheduling a remote session within the next few days

**Comment by unicorn-bi** [comment]
not able to reproduce this behavior yet. 

Things known to interrupt bluetooth previously:
- usb docking stations
- external usb monitor
- reinserting the usb dongle into different usb slots
- pairing a device, that was paired with another bluetooth dongle, with another bluetooth dongle again
- power saving flag enabled
- resource demanding apps like zoom or similar

Fixes:
- ensure that no external devices are connected and all other apps are closed
- unpair all devices and pair with the device from scrath
- ensure that the power saving flag is disabled

**Comment by flattinger** [comment]
Customer was using a third party Bluetooth dongle extender (with antenna). Told him to not use it and instead use the one from us.

**Comment by unicorn-bi** [comment]
Ok. Yes with the delivered bluetooth dongle the behavior was at least replicable.
